app = "qb1"

[build]
  # either leave blank for Dockerfile, or specify a builder:
  # builder = "Dockerfile"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
